--
-- PostgreSQL database dump
--

-- Dumped from database version 14.9
-- Dumped by pg_dump version 14.9

-- Started on 2023-12-06 19:45:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 41913)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 41912)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 41921)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 41920)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 41907)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 41906)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 42077)
-- Name: authenticate_car; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authenticate_car (
    id bigint NOT NULL,
    license_plate character varying(10) NOT NULL,
    brand character varying(100) NOT NULL,
    vin character varying(17) NOT NULL
);


ALTER TABLE public.authenticate_car OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 42076)
-- Name: authenticate_car_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authenticate_car ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authenticate_car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 42086)
-- Name: authenticate_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authenticate_employee (
    user_ptr_id bigint NOT NULL,
    employee_id character varying(10) NOT NULL,
    inn character varying(12) NOT NULL,
    "position" character varying NOT NULL
);


ALTER TABLE public.authenticate_employee OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 41953)
-- Name: authenticate_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authenticate_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    car_id bigint
);


ALTER TABLE public.authenticate_user OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 41963)
-- Name: authenticate_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authenticate_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authenticate_user_groups OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 41962)
-- Name: authenticate_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authenticate_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authenticate_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 41952)
-- Name: authenticate_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authenticate_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authenticate_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 41969)
-- Name: authenticate_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authenticate_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authenticate_user_user_permissions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 41968)
-- Name: authenticate_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authenticate_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authenticate_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 42004)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 42003)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 41899)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 41898)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 41891)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 41890)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 42066)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 42025)
-- Name: service_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_order (
    id bigint NOT NULL,
    final_price numeric(10,2) NOT NULL,
    created_time timestamp with time zone NOT NULL,
    status character varying NOT NULL,
    repair_request_id bigint,
    user_id bigint
);


ALTER TABLE public.service_order OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 42024)
-- Name: service_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 42049)
-- Name: service_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_orderitem (
    id bigint NOT NULL,
    item_price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    service_id bigint NOT NULL,
    spare_id bigint
);


ALTER TABLE public.service_orderitem OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 42048)
-- Name: service_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 42108)
-- Name: service_repairrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_repairrequest (
    id bigint NOT NULL,
    problem text NOT NULL,
    execution_deadline date,
    cost numeric(10,2)
);


ALTER TABLE public.service_repairrequest OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 42116)
-- Name: service_repairrequest_employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_repairrequest_employees (
    id bigint NOT NULL,
    repairrequest_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.service_repairrequest_employees OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 42115)
-- Name: service_repairrequest_employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_repairrequest_employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_repairrequest_employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 42107)
-- Name: service_repairrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_repairrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_repairrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 42122)
-- Name: service_repairrequest_services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_repairrequest_services (
    id bigint NOT NULL,
    repairrequest_id bigint NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.service_repairrequest_services OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 42121)
-- Name: service_repairrequest_services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_repairrequest_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_repairrequest_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 42033)
-- Name: service_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_service (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL
);


ALTER TABLE public.service_service OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 42032)
-- Name: service_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 42041)
-- Name: service_spare; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_spare (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    in_stock boolean NOT NULL,
    category character varying NOT NULL,
    image character varying(100)
);


ALTER TABLE public.service_spare OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 42040)
-- Name: service_spare_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_spare ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_spare_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3508 (class 0 OID 41913)
-- Dependencies: 216
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 3510 (class 0 OID 41921)
-- Dependencies: 218
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 3506 (class 0 OID 41907)
-- Dependencies: 214
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add order	6	add_order
22	Can change order	6	change_order
23	Can delete order	6	delete_order
24	Can view order	6	view_order
25	Can add service	7	add_service
26	Can change service	7	change_service
27	Can delete service	7	delete_service
28	Can view service	7	view_service
29	Can add spare	8	add_spare
30	Can change spare	8	change_spare
31	Can delete spare	8	delete_spare
32	Can view spare	8	view_spare
33	Can add order item	9	add_orderitem
34	Can change order item	9	change_orderitem
35	Can delete order item	9	delete_orderitem
36	Can view order item	9	view_orderitem
37	Can add user	10	add_user
38	Can change user	10	change_user
39	Can delete user	10	delete_user
40	Can view user	10	view_user
41	Can add repair request	11	add_repairrequest
42	Can change repair request	11	change_repairrequest
43	Can delete repair request	11	delete_repairrequest
44	Can view repair request	11	view_repairrequest
45	Can add car	12	add_car
46	Can change car	12	change_car
47	Can delete car	12	delete_car
48	Can view car	12	view_car
49	Can add user	13	add_employee
50	Can change user	13	change_employee
51	Can delete user	13	delete_employee
52	Can view user	13	view_employee
\.


--
-- TOC entry 3529 (class 0 OID 42077)
-- Dependencies: 237
-- Data for Name: authenticate_car; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authenticate_car (id, license_plate, brand, vin) FROM stdin;
1	1234567890	toyota	12345678901234567
2	4567891235	toyota	45678912351234567
3	7894561239	subaru	7894561231234567
\.


--
-- TOC entry 3530 (class 0 OID 42086)
-- Dependencies: 238
-- Data for Name: authenticate_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authenticate_employee (user_ptr_id, employee_id, inn, "position") FROM stdin;
\.


--
-- TOC entry 3512 (class 0 OID 41953)
-- Dependencies: 220
-- Data for Name: authenticate_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authenticate_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, car_id) FROM stdin;
2	pbkdf2_sha256$600000$gdGXLnEq4pjM5HILazk7E7$GMlJC+TNbBLywbf2dadeA712751rjkX5dH9Uj8eHLbQ=	2023-12-06 19:16:56.436273+03	f	testuser3				f	t	2023-12-04 07:04:12.716277+03	3
3	pbkdf2_sha256$600000$fImiCRlDoER64IyjpfS1Yz$ClFb3UPRQg57zImUw6QsdzIBgEp1kLJ0a13cHPzLClk=	2023-12-05 01:44:55.474613+03	t	adminuser				t	t	2023-12-05 01:44:26.479743+03	\N
1	pbkdf2_sha256$600000$LzW2ZFLYu4XGkKEGAtIEy6$KVuFFSs6ig1rln9cbCVWW/cyylFmNc6Rik74BfdslEQ=	2023-12-06 18:55:09.25938+03	f	testuser1	testuser1	testuser1		t	t	2023-11-18 18:58:45.389605+03	2
\.


--
-- TOC entry 3514 (class 0 OID 41963)
-- Dependencies: 222
-- Data for Name: authenticate_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authenticate_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 3516 (class 0 OID 41969)
-- Dependencies: 224
-- Data for Name: authenticate_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authenticate_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 3518 (class 0 OID 42004)
-- Dependencies: 226
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2023-12-05 01:45:14.158848+03	5	Spare object (5)	2	[{"changed": {"fields": ["Image"]}}]	8	3
\.


--
-- TOC entry 3504 (class 0 OID 41899)
-- Dependencies: 212
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	service	order
7	service	service
8	service	spare
9	service	orderitem
10	authenticate	user
11	service	repairrequest
12	authenticate	car
13	authenticate	employee
\.


--
-- TOC entry 3502 (class 0 OID 41891)
-- Dependencies: 210
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-11-16 00:13:32.702446+03
2	contenttypes	0002_remove_content_type_name	2023-11-16 00:13:32.717427+03
3	auth	0001_initial	2023-11-16 00:13:32.780462+03
4	auth	0002_alter_permission_name_max_length	2023-11-16 00:13:32.786461+03
5	auth	0003_alter_user_email_max_length	2023-11-16 00:13:32.794464+03
6	auth	0004_alter_user_username_opts	2023-11-16 00:13:32.800464+03
7	auth	0005_alter_user_last_login_null	2023-11-16 00:13:32.805463+03
8	auth	0006_require_contenttypes_0002	2023-11-16 00:13:32.808461+03
9	auth	0007_alter_validators_add_error_messages	2023-11-16 00:13:32.813481+03
10	auth	0008_alter_user_username_max_length	2023-11-16 00:13:32.820485+03
11	auth	0009_alter_user_last_name_max_length	2023-11-16 00:13:32.826489+03
12	auth	0010_alter_group_name_max_length	2023-11-16 00:13:32.840479+03
13	auth	0011_update_proxy_permissions	2023-11-16 00:13:32.846463+03
14	auth	0012_alter_user_first_name_max_length	2023-11-16 00:13:32.851462+03
15	authenticate	0001_initial	2023-11-16 00:13:32.904465+03
16	admin	0001_initial	2023-11-16 00:13:32.925471+03
17	admin	0002_logentry_remove_auto_add	2023-11-16 00:13:32.932469+03
18	admin	0003_logentry_add_action_flag_choices	2023-11-16 00:13:32.938864+03
19	service	0001_initial	2023-11-16 00:13:32.984501+03
20	sessions	0001_initial	2023-11-16 00:13:33.001497+03
21	authenticate	0002_car_employee_user_car	2023-11-16 00:59:36.276583+03
22	service	0002_alter_order_created_time_repairrequest_and_more	2023-11-16 00:59:36.342224+03
23	authenticate	0003_employee_position	2023-11-16 01:20:12.410768+03
24	service	0003_alter_order_created_time	2023-11-16 01:20:12.41776+03
25	service	0004_alter_order_created_time	2023-12-02 07:39:04.253517+03
26	service	0005_alter_order_created_time_alter_spare_in_stock	2023-12-02 07:40:24.280997+03
27	service	0006_alter_order_created_time_alter_spare_image	2023-12-02 07:41:17.564843+03
28	service	0007_alter_order_created_time_alter_repairrequest_cost_and_more	2023-12-04 07:20:49.436368+03
29	service	0008_order_user_alter_order_created_time	2023-12-05 05:54:57.221137+03
30	service	0009_orderitem_spare_alter_order_created_time	2023-12-05 11:01:06.98306+03
31	service	0010_alter_order_created_time_alter_orderitem_spare	2023-12-05 12:20:33.359202+03
\.


--
-- TOC entry 3527 (class 0 OID 42066)
-- Dependencies: 235
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
kj1vgib7mtqdh1n1svinrf09hwhpokcp	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r4Nkx:xEg6i-gkOFOEvmPyy9onBwaeKsPIxkoCSB-HNujQmag	2023-12-02 19:01:15.036127+03
dutfazlnnxyzx6wv2nltqghgg3k1nm40	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r4pMa:oOmheT75E6FwRAVRO0ggqn2WDS93GSr1yyRvzj6vJq4	2023-12-04 00:29:56.609888+03
ek1ki5736bcgbpvl417gjv0awg6wotvq	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r4puM:gr-stL8E1zXjdovEArVRlD7X0CnUMgbPeFLDHDe7WjI	2023-12-04 01:04:50.873464+03
lggk866wl7pzlkxe647o8mbniihgfa41	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9HJ9:ZaVhQz6-MtYQLEcI1PN_kykeJtpw2HYyraQE8PZfSGg	2023-12-16 07:08:47.29001+03
0tsh2clbo6769e4e43ozk57zwey5dhaa	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9IH3:fn-gR4sJvUeqeQt5UCVAEV5posfFiVReu3wa0DQnAPM	2023-12-16 08:10:41.547912+03
0vp7as5dv0vye7utyew6z1cr24rkjoom	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9IM3:5ClIdAufOEtKf8QsBj6eZQHPY3fuyxASCAfdu25u7yI	2023-12-16 08:15:51.516897+03
q3qpht8nrpuusy3m6ibhs2uf8s76ioi4	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9S4I:36O_PT1p_ZBGPUbHNif56D5sOm47BLwxh5GqGx-3J58	2023-12-16 18:38:10.864421+03
pfqgiegh36jpb44f80w3ah1nsmk2zenw	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9uNE:1thU7BKR-AdVeDIokz_Y0OpEJL5F5ZVxFZm8FeFO9Ew	2023-12-18 00:51:36.374878+03
4nbgyovqeajhf9z7t6tf5942cvoa8z4n	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9uXE:bwb2iBItkBM_2jvxx7G-yWcBY5ExcnZkcapIA9VA994	2023-12-18 01:01:56.817728+03
s99op3c80b98f4sfkhl2ke9z0uh9c9cn	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9woo:5dao25NwUQI7Viwfoj_bpUqH2b3Xfq7w7BW_JXDIaTw	2023-12-18 03:28:14.444868+03
ctpt8i1po7dzzbpwcb0ux9s1x09qqbhd	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xbZ:wv7AOj2eFUevUFZn-90R3wnT3BPgI3yIKf9LHU8KvsE	2023-12-18 04:18:37.826581+03
qvfwaa81kmdkxwkcx4q76tfzfwgsvpsr	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xdO:awqCz-duRZtRk2brosXu82qWjdsxDnKnO9mOeQpB1h8	2023-12-18 04:20:30.379548+03
iwck6co5in56faf8mnrk1guqu4acny4h	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xdp:6UDzBT_aWysGFjtJerOJEpSlraZn_8rd3lJp8iTNl8o	2023-12-18 04:20:57.236579+03
k7n14lbiml3giks8jsol0860sj5qzs6e	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xmV:GiLH8uRhRWj3w0n_OVSexA5IkuZ_IWReoU97lo4tsa0	2023-12-18 04:29:55.455738+03
eistg68qpt8xtjcek11hio9pgo9xx1e8	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xsM:iwFLxfDg7mK_8upK5Pse-4oj_2uEFkAgc4D0HEKtwEo	2023-12-18 04:35:58.554915+03
hqahs859n6f0cjh6zc3socsq2h0oyzk1	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xuJ:xYM3dOxH2wKR7gcGh5gEDpQGdz0-TgQ3OJkzXa6nmG8	2023-12-18 04:37:59.627111+03
3w7i9vrlcyy7q0tvl2do2qjhl9zysxl3	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xy3:P9zWOSBcS1YQ_krnIBCZkDFuE7mN8QY_X79FFFqPmyY	2023-12-18 04:41:51.797703+03
lxh1ml21o74a0cgoa0olhwrook78a218	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9xzb:7hKWozNWXENJhIXf36PWkQtzfcMPpdT61RCGbptIFJI	2023-12-18 04:43:27.909361+03
q9b3ywvv6y5ml31tv228bvrj0o58e6xj	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9y06:WpvhXqsH64-xyTyu5L8StZTjPMTD4qRKAh3xEUlDRXM	2023-12-18 04:43:58.640508+03
kqwkigd722u1rrx38btqsljxm4lms6la	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9y1n:AHdMrmao0m_f1zHLcIAbYuAi-aXP2wa8jNoQVHq-caQ	2023-12-18 04:45:43.928212+03
7wavzbd24qb2aeh8hqn83f5sebzqaxkx	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9y7N:Bc2Hy5m3Obf9r-YAj37Os1dOm5zBS8yTT2wEBM238wU	2023-12-18 04:51:29.622653+03
ec6spziyy7bnqa3rhtf2fn40qaz93yo0	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9y88:8lWRBNwByxGFTBjeQn6eDC8utmid19Gu40hgRpnL5hQ	2023-12-18 04:52:16.736913+03
cnz8kw33bx4vczlzc9t4dr03j1hrdzjq	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yA6:ekud9E-aDIwc3O2WsMeP0z4O5eBNBGsIjM6IYf7waBY	2023-12-18 04:54:18.879203+03
a3t479tml4oz326af3tuws4oojx86tkn	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yCE:6cqdOYCG1uieGjjKygmEy9sO1mDzP_MIKTP3jPKU5O8	2023-12-18 04:56:30.717874+03
ppgcl95csjxsiskutsq8u8re02z2yxnk	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yCq:uFEph_6Sk4ORLu8-mM3q3-cOduNxPrpHWMd3yvyFVG8	2023-12-18 04:57:08.456806+03
1pbutn0rn1hhe1hwlzed102ip0s5memy	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yGI:5Ak0KsfMTxx4rx9ZwvWF9ngg8keToIK51JXc_rfZ5EM	2023-12-18 05:00:42.448986+03
6m60wdhjguy8f4mod7q24o16jp6r888s	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQqf:kfp7N4TTz0EQIvweo1P47ls0m5jqAn-1qmv3aHgovCM	2023-12-19 11:32:09.81128+03
xsi1usyiif8irq22ju9nl02184ayfm9r	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yIY:5eDBxJsv8KEpGzHEhF4v0AmA5XdXg1EGI8r_SJOxZBU	2023-12-18 05:03:02.015836+03
v6ld9hsxqxcdcrpym5scd37qpq0vz8t9	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yJa:Zn1IEfBIQN0zljBYw_AeaZC2jKKVUzfRlg3PVr3bkdE	2023-12-18 05:04:06.687027+03
ajbpuuip2uszqbux2hmg3nadh6oytmbw	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yKE:hsUqCcb_TL8146QKpVHNc5nfvxlJvpK6W2i5TiFa9ww	2023-12-18 05:04:46.117146+03
xw4wexcex2on4cymsf29yikugyfyloim	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yae:F5nRToQ9DHTHHzYGxEyOPSHikSRLsaK3LvGYkDPMyXY	2023-12-18 05:21:44.955635+03
kzac0th30s4esjl492fgbvh8x7ww6z24	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9ydR:KX-A563KBg5CJeQoRPMYWBwm1zpcVXTAB-mf2HnQBvs	2023-12-18 05:24:37.436562+03
zs37h7lstgks7efpobkpkw7bq1lhe037	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yfA:2pA3QFUoiB6PAdadEoCQivLX-MYTtp41FphxFd3Yngk	2023-12-18 05:26:24.154439+03
aw3hu4tdd486goofk9m69awr6459z7mt	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yfP:QUscrAbN5N1_W9dxBQMOfxBdJdm4V5nTTr7JAblSGdc	2023-12-18 05:26:39.006065+03
yqlw56nabwbwky3njpg7p7cp4tukt6s7	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9yhO:VlN216pZsBchXHPzJY7nGw6tIcfXJoPzgZGhXKGV2R0	2023-12-18 05:28:42.22488+03
r9k5zdblkbgeq6z8tphy1blrhbexkk8s	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9ylC:0TU6NMEYdZHezq7ZPxirklwmhEBOqoCMwx4XU1xxBXg	2023-12-18 05:32:38.662685+03
sjzsl6ubdu7w7ws241yznzl6yqyzkxr8	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9ym2:4E3r-iyTsWthWrJ_Ygc2YchJi0qxDsEHsf-2rJ71acA	2023-12-18 05:33:30.233132+03
dwa8qt3nwzj9q2ev3dyn2qgo955h6jq9	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9zd3:UhTGquMuDdyQNg0p8VrpviWtDmyW_0NfQHnXsUDlU1w	2023-12-18 06:28:17.219142+03
n43g7yfxeqp069bwob7ky9egm1h2cb5o	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9zdu:wND6UQdiP3ACubF5Gh4l48W2RD213Ijvaa7LQ4hI6Wc	2023-12-18 06:29:10.620023+03
xdy0syodnmpdkc5mnad12iqhjt2o1nhi	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1r9zqG:gNEOlk7m7gphdnSqpLEpkQeULVacK9aZipSLSbGve9Q	2023-12-18 06:41:56.789795+03
047lo66vqm4yamae068sdeuq9iq2tcg5	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rA07a:drexypK74N3lsUZ1sQWQwduvcBMWK1KrjqsnLFIubSk	2023-12-18 06:59:50.99262+03
jw2niq96d8gyd46yvsulpiduthhnaa9c	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA0CO:1NryarZfH4yOPVCf52dP2jq3yIsIt4iRnumG_OsYki8	2023-12-18 07:04:48.669687+03
bwkm65rcfe8pqonz9e1wzo9fpuns2s0h	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA0E6:_XeVKdcLMVX-47R5CKSixuTTjJN_TTQ2FX-bM9YAQl4	2023-12-18 07:06:34.139728+03
7j0kysgpo4kf9omplvcds3ylqgcvecdn	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA0ET:xIphxDftCryJhaiKkgPUYnx8-FDBYnGqDgN9vM1D0HM	2023-12-18 07:06:57.141595+03
jgn2in2utxc1splk113op7jcf2nqu5iw	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA0J2:33nO1kg3lpI76lqtfjr0LGMawa3OnE5XRVDh6KdQuCA	2023-12-18 07:11:40.208794+03
t8d58cbxmcrh4ig07aesfjidbux61kcg	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA0Lo:b74iLQOiFeDZG__w_Ic2AayVU4DC4NWJVEOcdG4ZQnA	2023-12-18 07:14:32.237884+03
mchal9zia4kru5whb86cy2shp2h5ehxx	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rA2Gx:1cIovi9ds-RLWG4RKDTRXoPO0Kd3pLPrt98ibytgNeg	2023-12-18 09:17:39.886868+03
x4lbwswpqtinv3w1xmq5k4bokq72nf96	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAHWH:gouoAZLY_OVhnEsmA21PNzVtOwcdZD_D9eAml_U6JFg	2023-12-19 01:34:29.505538+03
es9uzrk7r0x8on87t75157lskpi2vy11	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAHY0:XTmznJBLNG0ZAFO9UEJZe8JtJU9tIw9SONonUBkZAck	2023-12-19 01:36:16.941003+03
xu9t2zgccup4ge6hemn4ta7z36zusjd7	.eJxVjMEOwiAQRP-FsyGlpSz16N1vIAu7SNVAUtqT8d8tSQ_1NjPvZT7C4bYmt1Ve3EziKgZxOW8ew4tzA_TE_CgylLwus5dNkQet8l6I37fD_TtIWFO7nZTm0RqA3qDiqBHA9poiQYcjRaWs7nxQFFpBJBspspn2MBjPQXx_39Y4zg:1rAHgN:SG9XzwevbAahaNgiHIsM-Ew0QETWpr5OvnpQu9wQxBw	2023-12-19 01:44:55.477984+03
lym48x83e4aqttxsxgc70at7cpqft0sl	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQXQ:IIXqgtI6VzjUnMkWYSsayKeU-XIp2peOoVSbZZ8wmIU	2023-12-19 11:12:16.427397+03
wbsyhg05oqm5jbx16d9i5ly9y1lmv3sl	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQZX:v02Clm_Oms_0U8mx7C9Dm60q1pX-qqL378Vos0vA8SI	2023-12-19 11:14:27.400654+03
oauwj7a3t3wzcro3chp1c6svy3mlwa3x	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQf1:GAi8PDDaa-7Tl4nFh4EAk-EaaDeWM4zOwYratYpSMSs	2023-12-19 11:20:07.72461+03
e2j6f000apsgapumskfjubyu901f9j3z	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQsN:z_cgKZTz19GE07NOmccyYQUUz5m2HMOk6Ky6jczjgx0	2023-12-19 11:33:55.329648+03
kte9u3hcphakvazdgb8l3ogn8hl4gjg3	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQhF:sc6YGu7b2lRtyN3KYXZw3Rhl-STjqNZsuIgyAnfgm9I	2023-12-19 11:22:25.354222+03
6lysgifcas09e4g76qr740j5g2nbco7h	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAR7s:zoDhdW5mIHNaI0nElDK6EeFTsfQVKKC0pXSafuMiE5I	2023-12-19 11:49:56.02287+03
9oyjoa2vd8fdnydj5bloqw90obqbvnoi	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQho:k6EEdxRo3WzvFj5UHEZDFe9PoRUDflXTJPAkzOtPg3Y	2023-12-19 11:23:00.486399+03
iit5zrvfacgrngd43lv0fumpvystejk9	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAR9d:ePnXV0uVnBlZLehhnqEg9XCU2LlQcVhCSD2q6iD0IDE	2023-12-19 11:51:45.120167+03
vjw4qxs6ziaorj396nqcnmo3zo7tnjbj	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAQio:ibRubV87ZgPbVbvwFQ9CfyT7gVJ56vAJN2iXVV0hwzU	2023-12-19 11:24:02.859168+03
la6gtfdyimqh8wx7jl3607c6f0zkca2y	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rARLA:Jzh7m6fbaHnACNF0YIK8JGEfStMcVi_gijf22L7jRE4	2023-12-19 12:03:40.41844+03
npsnu8qmvwngugyskcmeer0cwtbl1t29	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rARLm:eKqFs6J5IoROeqfNIoYOK7tAD-_QWwrQQQYtAEkog9g	2023-12-19 12:04:18.526528+03
0ze6fhojq003hq5aiqvh4zeaz1000522	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rARPW:nNfdwwLGjkVBrwzK0CqzuMe3IYzPtuW-Ll-7XLqyDT8	2023-12-19 12:08:10.621+03
lm5pkinvcov9si2utmnjkzpv9oou2fsa	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rARUR:NiFnro3M4BUsVkPvo3LC8SzRzyDrV9jm7soNSUiw0gU	2023-12-19 12:13:15.638098+03
s3su21gog4s1n0ueh502k174jnbe550e	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rARZQ:h8_TsporImYT1yIA9_BRheC6HAcdcOCepq5ORGJawow	2023-12-19 12:18:24.871248+03
7t1c8898y1hi7w0lg5u4b0mtkj811kkx	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAWuS:jFAEO59q41euCa-J_hldOpiiCTeuJL2WdDvBjHQ0csA	2023-12-19 18:00:28.010602+03
sy1qz9z8dlwuo74vxjt4rj5hhsoxhoo7	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAX6j:iwDYyuAAuQUsOLoLWRElhaUWZXuXQdhjCQZ1xwISNgs	2023-12-19 18:13:09.55408+03
dq1vk9npkscsp28dax4bfyfuk2mt9ynb	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXIn:zfr936p1WVdVWlHMxQKV1rP3-QTl6MT23jBCIBMhmHA	2023-12-19 18:25:37.815446+03
w0u1c3rnmaydz5iwwzp6jjuqpctnhrx6	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXKK:6aFSBkaTxaVJzPtW3qWGYLbAwApm_AiRKAplvcFpDhU	2023-12-19 18:27:12.891392+03
aarqyn0i2tl11k3vj5wguik9lg1qif1i	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXj2:wqlgB0Kg4serqshEnNdYhv7Po6PHHPKh1YfQJi7nqjQ	2023-12-19 18:52:44.457404+03
i13rzp16a25yjj7c4jna0kf47y4ftbzp	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXkA:g6tcCqkhiXRbrMpUBJhYa1peN2dTkunGxMxjXFGAmlo	2023-12-19 18:53:54.26794+03
kpx4xeqlfupnc6q2vx08cbmq3qfldzaf	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXn3:9ZoANeJnBC8_fAxiA-81iReLDvpKr2Jkg1He_zGybXI	2023-12-19 18:56:53.826389+03
ongijo97iiaqgpe0c2nm8w29nfyy7hyd	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXnw:xq49-6JfN3_teO0bxCltHBGG3V0OP0Z4dXaPas0vqKo	2023-12-19 18:57:48.981023+03
5yst6eskw3xoxgp9dd8kyqngt9jo1rd0	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXoq:0e56z74MHcdwg0-iYxUBKBxlqJxZCYR1z1zUiB-nIHk	2023-12-19 18:58:44.233158+03
w6wtjp3rrxxh6phxzgoketa3fcnb1bz8	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAXra:v_4bKMF-nlUgZ6a4-p9yf6-KAR3tH5IBjzfOBk9l1-M	2023-12-19 19:01:34.801476+03
qsmedb9gnnfzecrk3u3o7yk1ecw80ns7	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAXv2:0bfRZnprfEzwfUMCoZ8oc1vte8aDVzUhA9Q8gNKs4Cs	2023-12-19 19:05:08.257557+03
mqhzpyd6evf5mqlnrg78l43iu90oyg4k	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAXyk:hzo8yxWuqPKgbTOF-EmLT7YNJbb_AS6_uhT_Z5kqKTk	2023-12-19 19:08:58.139451+03
bbx2kkbod1n55pqebf71kikdohujpp06	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAY4a:RWHTy046UMY7wc8kxEYuO30FebW1ZT7aTNPVbWqX7lA	2023-12-19 19:15:00.071123+03
147tc15laolyw4on33ujc427mzu2f2jm	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAY4l:P4aeSuJsTpVaQNyMRZ2oKpxWtX5bfAYobgB0T4UyFTs	2023-12-19 19:15:11.712265+03
980ubndqjwae21va1yj48jg0ed8ufucl	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAYX6:zXV9DTShqpSM-YjjdlN4dMMnr0G25bo1n6lLF79uV4Q	2023-12-19 19:44:28.080976+03
6cvnotnptve6gtqrk0dzqo2i2xv020xj	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAYZJ:2-x4PQYadM-m0kvLoI4_-PjvWRg1MjsX_XR__9EnMuM	2023-12-19 19:46:45.597442+03
b4ssjxw6pjahzjl63a5d64o78okm83lm	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAYkM:OSw7wy_IDb1yJPg7kDU92TLu1-J1xKkWXj7ANERXjAQ	2023-12-19 19:58:10.652274+03
dvqfrzyhw1pwx0y56eu5upsrlsyt5iz6	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAYkW:2gDLGVKQih4W5mljT3TcPuwRQxO1-yQNBJtDGO0BwyE	2023-12-19 19:58:20.683123+03
juflpklbu3zogsm7kiysiwnze24wrnaw	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAYwM:GgHY14giWtQzkHJAbUUDUFg9ZVd-4gEBsr7OmB5xosQ	2023-12-19 20:10:34.406818+03
rsp1yegu39aqs5byudxpfib8nzpxkz0i	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAYwc:qQc4AUbwIDeZ5ha5VmJXKsRMujSW3eSeE7YlwGKlB34	2023-12-19 20:10:50.587828+03
0wg1ul5he8tfvzac8q3jt4wi1af2jxbz	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAZ9H:Zyf662GbTwY2v1GKb0g_krV517NX7zUB8sRMtqvdqK8	2023-12-19 20:23:55.516978+03
gzmrs71jim7ynntpbunfdynkb3olj99a	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAZ9d:LUMKe539RJ8sOxmXjUbyek8wc5tEDBEqwxD_21FWwks	2023-12-19 20:24:17.472665+03
viv3j7gbw8aoglu49yddghlxmjwy5vlv	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAZDe:1mLoZrLTHO2J66zIKPR0y_68yArBvWCc2ujMfxJ5BQE	2023-12-19 20:28:26.228162+03
oo4il6di9hcwx0nr96pprfmc4i7ptu7o	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAZuI:6xSwD031O8gzTPgsp7GnlICau1EfQG-6lS5bzpZrUI0	2023-12-19 21:12:30.387852+03
rh4lpd5zgsxde8oemhrcgkprxfkitja1	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAZuU:ZnNOLHcsQ5nZgQXICKs7Fm7GWPxrXNz4HtV4_lYIxYw	2023-12-19 21:12:42.587471+03
n1308h3bk1t8lh1prjyr2klr1v6xif67	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAa77:F61OMbq7c2wtnNnIR3hwQYZEU0NigLObnXTWIu9DMYw	2023-12-19 21:25:45.899073+03
i4ukxdmqfc0mtyn7tvteu5uxwdch8xvb	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAa7I:PF3suL7pcGY4E2E8ofWbcSikPtITxso_-xBimLM_zuU	2023-12-19 21:25:56.033323+03
a71hbg54exd4x5j5n9eluvmnz53as8vo	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAaAj:D6IQ9pM6DvTxXfU-AVGV5DAyMuW385GTcSGlPFp1EUo	2023-12-19 21:29:29.601772+03
o1lqwi12nszypwjjaducw0phgk31dhsk	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAaBG:VNrVfsiVQTf_t_vigFH2zp07hiuhGUwTDnbrXOyiPFs	2023-12-19 21:30:02.938399+03
nir8ux9ec7wvnqr5xro8g8xjbz62hbvp	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAaCx:eTJxs26K0wRekoThhpMFMVtQNbFxTRh6moDtjXD_caY	2023-12-19 21:31:47.491343+03
8qkel0ovhso5hlmjsr33o6893y2afdbi	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAtYb:Wx_Oyrt9Lkx4CgUYL3u4GlidBxmAKNv8IY-JC-2rwos	2023-12-20 18:11:25.648951+03
siitsiy4cya00jxfm6zxr998kkzh7y9d	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAtZ1:ONGuX5i1Vm5fnAW_DDC0WR2z2RjQ21GkhSH0A73vLSY	2023-12-20 18:11:51.338373+03
kdwbo54vx987om3753kwxjxrzh5aap2r	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAtuz:KUYRqGV0dkqq5TQQcjyfK0r_dhNM6g8cOktzRZMKznk	2023-12-20 18:34:33.777283+03
kf9jp3nr90b67x2n9jbnlus6p4l019sx	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAtyR:S7_-6_Z3jOHTRrynPKCjX1qmTaPsUwdxcZh6NwWXolQ	2023-12-20 18:38:07.017331+03
j7tlgt8a3igtufdpw9gceqzpyjwoagnr	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAtzL:ngoezfpEI0Onyp_dKiBddQ41S2NDphr6DC68mGKyoao	2023-12-20 18:39:03.397369+03
99ndd23i93ta0qlwx5iogr63na7kxcv3	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAu5h:IMVdTm4AUdWTJnp7rnRS89D-aavg4g86Qu6raWfwxPo	2023-12-20 18:45:37.852353+03
u0cthfl8i9isa0dbkr55smu06s21oeg8	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAu61:LmezXDjF0PMzvYyKVStgj_NZ4ydjmcoLzZ6Tr0mcwnk	2023-12-20 18:45:57.977582+03
o48rilg8ukkg98skl1giickyeefr4430	.eJxVjMsOwiAQRf-FtSFlmIK4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguQonT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbG6cBkYmtAh3RMGBmOyYTFNloWGedwcGAZ8pIyoUxOUJKYWBnlAbx_gDYcTfE:1rAuEv:WF_GHuLU_0HDjNG4EE0cFsrbiNCjrSkuslJg1Ox63wY	2023-12-20 18:55:09.289397+03
6c4r9ucvlhknlzjpvq48pai6ynbh9fmj	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAuF9:9zImqZnB6wrctic8PTYBAwa2cHyB6OKxepVHTPv5TD0	2023-12-20 18:55:23.490246+03
gh7m3ohbz98ooudyter7nakkkk92z4dt	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAuJV:_PrIzPgIsqUrexLOUgcvcze5PJ2LsqDkV4fq8LOMVBs	2023-12-20 18:59:53.583553+03
j21ojo7jwncvcl0oak5gg993fs14ahgy	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAuTX:SNQZ1m2WzMKPFa-BSsYhzg54E1K9REJKO_Yh-Bxfjj8	2023-12-20 19:10:15.634612+03
j0fycz6h1drydb6vmwj50dot0y6yvy8n	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAuXR:4Q54sM-YlJvweswnwEBilaG2YOs8mvx5ycK8jifrK_k	2023-12-20 19:14:17.990951+03
e8ptgagtjj6a6uwqgvfk5tap6zi0u7t2	.eJxVjMEOwiAQBf-FsyGwQAGP3v0GssAiVQNJaU_Gf9cmPej1zcx7sYDbWsM2aAlzZmcG7PS7RUwPajvId2y3zlNv6zJHviv8oINfe6bn5XD_DiqO-q0daaG1BB8deIUWVJYle_LFobVOEpGdKCZrUCkpYnTOqzJ5A0YkkJm9P84zN1k:1rAua0:iiVoFeK9zXm57U4rTm2N33SFpE8yXN24qy-njcupNyM	2023-12-20 19:16:56.459859+03
\.


--
-- TOC entry 3520 (class 0 OID 42025)
-- Dependencies: 228
-- Data for Name: service_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_order (id, final_price, created_time, status, repair_request_id, user_id) FROM stdin;
1	100.00	2023-12-05 08:08:14.182535+03	in process	\N	\N
2	0.00	2023-12-05 08:55:08.140289+03	in process	\N	\N
3	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
4	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
5	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
6	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
7	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
8	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
9	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
10	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
11	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
12	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
13	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
14	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
15	0.00	2023-12-05 14:01:33.687567+03	in process	\N	1
16	0.00	2023-12-06 00:36:06.818768+03	in process	\N	2
17	0.00	2023-12-06 21:11:02.145023+03	in process	\N	1
18	0.00	2023-12-06 21:11:02.145023+03	in process	\N	1
19	0.00	2023-12-06 21:11:02.145023+03	in process	\N	2
20	0.00	2023-12-06 21:11:02.145023+03	in process	\N	1
21	0.00	2023-12-06 21:11:02.145023+03	in process	\N	2
22	0.00	2023-12-06 21:11:02.145023+03	in process	\N	1
23	0.00	2023-12-06 21:11:02.145023+03	in process	\N	2
24	0.00	2023-12-06 21:54:31.596086+03	in process	\N	1
25	0.00	2023-12-06 21:54:31.596086+03	in process	\N	2
26	0.00	2023-12-06 21:54:31.596086+03	in process	\N	2
27	0.00	2023-12-06 21:54:31.596086+03	in process	\N	2
28	0.00	2023-12-06 21:54:31.596086+03	in process	\N	2
\.


--
-- TOC entry 3526 (class 0 OID 42049)
-- Dependencies: 234
-- Data for Name: service_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_orderitem (id, item_price, order_id, service_id, spare_id) FROM stdin;
1	1000.00	1	1	4
2	100.00	14	1	\N
3	100.00	15	1	4
4	100.00	16	1	4
\.


--
-- TOC entry 3532 (class 0 OID 42108)
-- Dependencies: 240
-- Data for Name: service_repairrequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_repairrequest (id, problem, execution_deadline, cost) FROM stdin;
10	Как писать чаты	\N	\N
11	Как писать чаты	\N	\N
12	Как писать чаты 2	\N	\N
13	Как писать чаты 2	\N	\N
14	Nothing	\N	\N
15	Nothing	\N	\N
16	Как писать чаты 123	\N	\N
17	Nothing	\N	\N
18	Nothing	\N	\N
19	Nothing	\N	\N
20	Nothing	\N	\N
21	Nothing	\N	\N
22	Как писать чаты321	\N	\N
23	Как писать чаты 456	\N	\N
24	Nothing	\N	\N
25	Nothing	\N	\N
26	Nothing	\N	\N
27	Nothing	\N	\N
28	Nothing	\N	\N
29	Nothing	\N	\N
30	Как писать чаты	\N	\N
\.


--
-- TOC entry 3534 (class 0 OID 42116)
-- Dependencies: 242
-- Data for Name: service_repairrequest_employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_repairrequest_employees (id, repairrequest_id, employee_id) FROM stdin;
\.


--
-- TOC entry 3536 (class 0 OID 42122)
-- Dependencies: 244
-- Data for Name: service_repairrequest_services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_repairrequest_services (id, repairrequest_id, service_id) FROM stdin;
\.


--
-- TOC entry 3522 (class 0 OID 42033)
-- Dependencies: 230
-- Data for Name: service_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_service (id, name, description, price) FROM stdin;
1	service1	service1	100.00
2	service2	service2	200.00
\.


--
-- TOC entry 3524 (class 0 OID 42041)
-- Dependencies: 232
-- Data for Name: service_spare; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_spare (id, name, description, price, in_stock, category, image) FROM stdin;
4	testspare1	testspare1	100.00	t	body	
5	testsapre2	testsapre2	150.00	t	body	spares/Null_catalog.png
\.


--
-- TOC entry 3542 (class 0 OID 0)
-- Dependencies: 215
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 3543 (class 0 OID 0)
-- Dependencies: 217
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 3544 (class 0 OID 0)
-- Dependencies: 213
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- TOC entry 3545 (class 0 OID 0)
-- Dependencies: 236
-- Name: authenticate_car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authenticate_car_id_seq', 3, true);


--
-- TOC entry 3546 (class 0 OID 0)
-- Dependencies: 221
-- Name: authenticate_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authenticate_user_groups_id_seq', 1, false);


--
-- TOC entry 3547 (class 0 OID 0)
-- Dependencies: 219
-- Name: authenticate_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authenticate_user_id_seq', 3, true);


--
-- TOC entry 3548 (class 0 OID 0)
-- Dependencies: 223
-- Name: authenticate_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authenticate_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 3549 (class 0 OID 0)
-- Dependencies: 225
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- TOC entry 3550 (class 0 OID 0)
-- Dependencies: 211
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- TOC entry 3551 (class 0 OID 0)
-- Dependencies: 209
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- TOC entry 3552 (class 0 OID 0)
-- Dependencies: 227
-- Name: service_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_order_id_seq', 28, true);


--
-- TOC entry 3553 (class 0 OID 0)
-- Dependencies: 233
-- Name: service_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_orderitem_id_seq', 4, true);


--
-- TOC entry 3554 (class 0 OID 0)
-- Dependencies: 241
-- Name: service_repairrequest_employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_repairrequest_employees_id_seq', 1, false);


--
-- TOC entry 3555 (class 0 OID 0)
-- Dependencies: 239
-- Name: service_repairrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_repairrequest_id_seq', 30, true);


--
-- TOC entry 3556 (class 0 OID 0)
-- Dependencies: 243
-- Name: service_repairrequest_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_repairrequest_services_id_seq', 1, false);


--
-- TOC entry 3557 (class 0 OID 0)
-- Dependencies: 229
-- Name: service_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_service_id_seq', 2, true);


--
-- TOC entry 3558 (class 0 OID 0)
-- Dependencies: 231
-- Name: service_spare_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_spare_id_seq', 5, true);


--
-- TOC entry 3266 (class 2606 OID 41950)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3271 (class 2606 OID 41936)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3274 (class 2606 OID 41925)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 41917)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3261 (class 2606 OID 41927)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3263 (class 2606 OID 41911)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3317 (class 2606 OID 42083)
-- Name: authenticate_car authenticate_car_license_plate_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_car
    ADD CONSTRAINT authenticate_car_license_plate_key UNIQUE (license_plate);


--
-- TOC entry 3319 (class 2606 OID 42081)
-- Name: authenticate_car authenticate_car_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_car
    ADD CONSTRAINT authenticate_car_pkey PRIMARY KEY (id);


--
-- TOC entry 3322 (class 2606 OID 42085)
-- Name: authenticate_car authenticate_car_vin_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_car
    ADD CONSTRAINT authenticate_car_vin_key UNIQUE (vin);


--
-- TOC entry 3325 (class 2606 OID 42092)
-- Name: authenticate_employee authenticate_employee_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_employee
    ADD CONSTRAINT authenticate_employee_employee_id_key UNIQUE (employee_id);


--
-- TOC entry 3327 (class 2606 OID 42090)
-- Name: authenticate_employee authenticate_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_employee
    ADD CONSTRAINT authenticate_employee_pkey PRIMARY KEY (user_ptr_id);


--
-- TOC entry 3283 (class 2606 OID 41967)
-- Name: authenticate_user_groups authenticate_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_groups
    ADD CONSTRAINT authenticate_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3286 (class 2606 OID 41976)
-- Name: authenticate_user_groups authenticate_user_groups_user_id_group_id_354227fa_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_groups
    ADD CONSTRAINT authenticate_user_groups_user_id_group_id_354227fa_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 3277 (class 2606 OID 41959)
-- Name: authenticate_user authenticate_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user
    ADD CONSTRAINT authenticate_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3288 (class 2606 OID 41990)
-- Name: authenticate_user_user_permissions authenticate_user_user_p_user_id_permission_id_b0f0644e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_user_permissions
    ADD CONSTRAINT authenticate_user_user_p_user_id_permission_id_b0f0644e_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 3291 (class 2606 OID 41973)
-- Name: authenticate_user_user_permissions authenticate_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_user_permissions
    ADD CONSTRAINT authenticate_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3280 (class 2606 OID 41961)
-- Name: authenticate_user authenticate_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user
    ADD CONSTRAINT authenticate_user_username_key UNIQUE (username);


--
-- TOC entry 3295 (class 2606 OID 42011)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3256 (class 2606 OID 41905)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3258 (class 2606 OID 41903)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3254 (class 2606 OID 41897)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3313 (class 2606 OID 42072)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3298 (class 2606 OID 42031)
-- Name: service_order service_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_order
    ADD CONSTRAINT service_order_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 42128)
-- Name: service_order service_order_repair_request_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_order
    ADD CONSTRAINT service_order_repair_request_id_key UNIQUE (repair_request_id);


--
-- TOC entry 3308 (class 2606 OID 42053)
-- Name: service_orderitem service_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_orderitem
    ADD CONSTRAINT service_orderitem_pkey PRIMARY KEY (id);


--
-- TOC entry 3331 (class 2606 OID 42135)
-- Name: service_repairrequest_employees service_repairrequest_em_repairrequest_id_employe_bf7bac1d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_employees
    ADD CONSTRAINT service_repairrequest_em_repairrequest_id_employe_bf7bac1d_uniq UNIQUE (repairrequest_id, employee_id);


--
-- TOC entry 3334 (class 2606 OID 42120)
-- Name: service_repairrequest_employees service_repairrequest_employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_employees
    ADD CONSTRAINT service_repairrequest_employees_pkey PRIMARY KEY (id);


--
-- TOC entry 3329 (class 2606 OID 42114)
-- Name: service_repairrequest service_repairrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest
    ADD CONSTRAINT service_repairrequest_pkey PRIMARY KEY (id);


--
-- TOC entry 3337 (class 2606 OID 42149)
-- Name: service_repairrequest_services service_repairrequest_se_repairrequest_id_service_a825896e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_services
    ADD CONSTRAINT service_repairrequest_se_repairrequest_id_service_a825896e_uniq UNIQUE (repairrequest_id, service_id);


--
-- TOC entry 3339 (class 2606 OID 42126)
-- Name: service_repairrequest_services service_repairrequest_services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_services
    ADD CONSTRAINT service_repairrequest_services_pkey PRIMARY KEY (id);


--
-- TOC entry 3303 (class 2606 OID 42039)
-- Name: service_service service_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_service
    ADD CONSTRAINT service_service_pkey PRIMARY KEY (id);


--
-- TOC entry 3305 (class 2606 OID 42047)
-- Name: service_spare service_spare_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_spare
    ADD CONSTRAINT service_spare_pkey PRIMARY KEY (id);


--
-- TOC entry 3264 (class 1259 OID 41951)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3269 (class 1259 OID 41947)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3272 (class 1259 OID 41948)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3259 (class 1259 OID 41933)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3315 (class 1259 OID 42098)
-- Name: authenticate_car_license_plate_86f4c100_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_car_license_plate_86f4c100_like ON public.authenticate_car USING btree (license_plate varchar_pattern_ops);


--
-- TOC entry 3320 (class 1259 OID 42099)
-- Name: authenticate_car_vin_091f063f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_car_vin_091f063f_like ON public.authenticate_car USING btree (vin varchar_pattern_ops);


--
-- TOC entry 3323 (class 1259 OID 42105)
-- Name: authenticate_employee_employee_id_f5c711a3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_employee_employee_id_f5c711a3_like ON public.authenticate_employee USING btree (employee_id varchar_pattern_ops);


--
-- TOC entry 3275 (class 1259 OID 42106)
-- Name: authenticate_user_car_id_b56959d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_car_id_b56959d1 ON public.authenticate_user USING btree (car_id);


--
-- TOC entry 3281 (class 1259 OID 41988)
-- Name: authenticate_user_groups_group_id_9b715d1a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_groups_group_id_9b715d1a ON public.authenticate_user_groups USING btree (group_id);


--
-- TOC entry 3284 (class 1259 OID 41987)
-- Name: authenticate_user_groups_user_id_03af5d64; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_groups_user_id_03af5d64 ON public.authenticate_user_groups USING btree (user_id);


--
-- TOC entry 3289 (class 1259 OID 42002)
-- Name: authenticate_user_user_permissions_permission_id_99b44b6f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_user_permissions_permission_id_99b44b6f ON public.authenticate_user_user_permissions USING btree (permission_id);


--
-- TOC entry 3292 (class 1259 OID 42001)
-- Name: authenticate_user_user_permissions_user_id_87f63292; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_user_permissions_user_id_87f63292 ON public.authenticate_user_user_permissions USING btree (user_id);


--
-- TOC entry 3278 (class 1259 OID 41974)
-- Name: authenticate_user_username_171aad7d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authenticate_user_username_171aad7d_like ON public.authenticate_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 3293 (class 1259 OID 42022)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3296 (class 1259 OID 42023)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3311 (class 1259 OID 42074)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3314 (class 1259 OID 42073)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3301 (class 1259 OID 57360)
-- Name: service_order_user_id_3966099d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_order_user_id_3966099d ON public.service_order USING btree (user_id);


--
-- TOC entry 3306 (class 1259 OID 42064)
-- Name: service_orderitem_order_id_8858ea60; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_orderitem_order_id_8858ea60 ON public.service_orderitem USING btree (order_id);


--
-- TOC entry 3309 (class 1259 OID 42065)
-- Name: service_orderitem_service_id_a321f88d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_orderitem_service_id_a321f88d ON public.service_orderitem USING btree (service_id);


--
-- TOC entry 3310 (class 1259 OID 57370)
-- Name: service_orderitem_spare_id_cb03df6e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_orderitem_spare_id_cb03df6e ON public.service_orderitem USING btree (spare_id);


--
-- TOC entry 3332 (class 1259 OID 42147)
-- Name: service_repairrequest_employees_employee_id_ab8322e3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_repairrequest_employees_employee_id_ab8322e3 ON public.service_repairrequest_employees USING btree (employee_id);


--
-- TOC entry 3335 (class 1259 OID 42146)
-- Name: service_repairrequest_employees_repairrequest_id_73d928b3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_repairrequest_employees_repairrequest_id_73d928b3 ON public.service_repairrequest_employees USING btree (repairrequest_id);


--
-- TOC entry 3340 (class 1259 OID 42160)
-- Name: service_repairrequest_services_repairrequest_id_d3808eca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_repairrequest_services_repairrequest_id_d3808eca ON public.service_repairrequest_services USING btree (repairrequest_id);


--
-- TOC entry 3341 (class 1259 OID 42161)
-- Name: service_repairrequest_services_service_id_01e70d36; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX service_repairrequest_services_service_id_01e70d36 ON public.service_repairrequest_services USING btree (service_id);


--
-- TOC entry 3344 (class 2606 OID 41942)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3343 (class 2606 OID 41937)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3342 (class 2606 OID 41928)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3357 (class 2606 OID 42100)
-- Name: authenticate_employee authenticate_employe_user_ptr_id_df36ed2f_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_employee
    ADD CONSTRAINT authenticate_employe_user_ptr_id_df36ed2f_fk_authentic FOREIGN KEY (user_ptr_id) REFERENCES public.authenticate_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3345 (class 2606 OID 42093)
-- Name: authenticate_user authenticate_user_car_id_b56959d1_fk_authenticate_car_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user
    ADD CONSTRAINT authenticate_user_car_id_b56959d1_fk_authenticate_car_id FOREIGN KEY (car_id) REFERENCES public.authenticate_car(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3346 (class 2606 OID 41977)
-- Name: authenticate_user_groups authenticate_user_gr_user_id_03af5d64_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_groups
    ADD CONSTRAINT authenticate_user_gr_user_id_03af5d64_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authenticate_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3347 (class 2606 OID 41982)
-- Name: authenticate_user_groups authenticate_user_groups_group_id_9b715d1a_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_groups
    ADD CONSTRAINT authenticate_user_groups_group_id_9b715d1a_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3349 (class 2606 OID 41996)
-- Name: authenticate_user_user_permissions authenticate_user_us_permission_id_99b44b6f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_user_permissions
    ADD CONSTRAINT authenticate_user_us_permission_id_99b44b6f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3348 (class 2606 OID 41991)
-- Name: authenticate_user_user_permissions authenticate_user_us_user_id_87f63292_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authenticate_user_user_permissions
    ADD CONSTRAINT authenticate_user_us_user_id_87f63292_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authenticate_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3350 (class 2606 OID 42012)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3351 (class 2606 OID 42017)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authenticate_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authenticate_user_id FOREIGN KEY (user_id) REFERENCES public.authenticate_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3352 (class 2606 OID 42129)
-- Name: service_order service_order_repair_request_id_d02a9836_fk_service_r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_order
    ADD CONSTRAINT service_order_repair_request_id_d02a9836_fk_service_r FOREIGN KEY (repair_request_id) REFERENCES public.service_repairrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3353 (class 2606 OID 57355)
-- Name: service_order service_order_user_id_3966099d_fk_authenticate_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_order
    ADD CONSTRAINT service_order_user_id_3966099d_fk_authenticate_user_id FOREIGN KEY (user_id) REFERENCES public.authenticate_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3354 (class 2606 OID 42054)
-- Name: service_orderitem service_orderitem_order_id_8858ea60_fk_service_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_orderitem
    ADD CONSTRAINT service_orderitem_order_id_8858ea60_fk_service_order_id FOREIGN KEY (order_id) REFERENCES public.service_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3355 (class 2606 OID 42059)
-- Name: service_orderitem service_orderitem_service_id_a321f88d_fk_service_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_orderitem
    ADD CONSTRAINT service_orderitem_service_id_a321f88d_fk_service_service_id FOREIGN KEY (service_id) REFERENCES public.service_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3356 (class 2606 OID 57371)
-- Name: service_orderitem service_orderitem_spare_id_cb03df6e_fk_service_spare_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_orderitem
    ADD CONSTRAINT service_orderitem_spare_id_cb03df6e_fk_service_spare_id FOREIGN KEY (spare_id) REFERENCES public.service_spare(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3359 (class 2606 OID 42141)
-- Name: service_repairrequest_employees service_repairreques_employee_id_ab8322e3_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_employees
    ADD CONSTRAINT service_repairreques_employee_id_ab8322e3_fk_authentic FOREIGN KEY (employee_id) REFERENCES public.authenticate_employee(user_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3358 (class 2606 OID 42136)
-- Name: service_repairrequest_employees service_repairreques_repairrequest_id_73d928b3_fk_service_r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_employees
    ADD CONSTRAINT service_repairreques_repairrequest_id_73d928b3_fk_service_r FOREIGN KEY (repairrequest_id) REFERENCES public.service_repairrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3360 (class 2606 OID 42150)
-- Name: service_repairrequest_services service_repairreques_repairrequest_id_d3808eca_fk_service_r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_services
    ADD CONSTRAINT service_repairreques_repairrequest_id_d3808eca_fk_service_r FOREIGN KEY (repairrequest_id) REFERENCES public.service_repairrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3361 (class 2606 OID 42155)
-- Name: service_repairrequest_services service_repairreques_service_id_01e70d36_fk_service_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_repairrequest_services
    ADD CONSTRAINT service_repairreques_service_id_01e70d36_fk_service_s FOREIGN KEY (service_id) REFERENCES public.service_service(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2023-12-06 19:45:27

--
-- PostgreSQL database dump complete
--

CREATE VIEW public.virtual_user_car_info AS
SELECT
    au.id AS user_id,
    au.username,
    au.email,
    ac.id AS car_id,
    ac.license_plate,
    ac.brand,
    ac.vin
FROM
    public.authenticate_user au
JOIN
    public.authenticate_car ac ON au.car_id = ac.id;

CREATE VIEW public.virtual_repair_service_info AS
SELECT
    sr.id AS repair_request_id,
    sr.problem,
    ss.id AS service_id,
    ss.name AS service_name,
    ss.description AS service_description,
    ss.price AS service_price
FROM
    public.service_repairrequest sr
JOIN
    public.service_repairrequest_services srs ON sr.id = srs.repairrequest_id
JOIN
    public.service_service ss ON srs.service_id = ss.id;


CREATE OR REPLACE PROCEDURE public.add_user_with_car(
    p_username VARCHAR(150),
    p_email VARCHAR(254),
    p_password VARCHAR(128),
    p_license_plate VARCHAR(10),
    p_brand VARCHAR(100),
    p_vin VARCHAR(17)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_user_id bigint;
    v_car_id bigint;
BEGIN
    -- Добавление пользователя
    INSERT INTO public.authenticate_user(username, email, password, is_superuser, first_name, last_name, is_staff, is_active, date_joined)
    VALUES (p_username, p_email, p_password, false, 'First', 'Last', false, true, NOW())
    RETURNING id INTO v_user_id;

    -- Добавление автомобиля
    INSERT INTO public.authenticate_car(license_plate, brand, vin)
    VALUES (p_license_plate, p_brand, p_vin)
    RETURNING id INTO v_car_id;

    -- Обновление пользователя с информацией об автомобиле
    UPDATE public.authenticate_user
    SET car_id = v_car_id
    WHERE id = v_user_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.create_repair_request(
    p_problem TEXT,
    p_execution_deadline DATE,
    p_cost NUMERIC(10, 2),
    p_services INTEGER[]
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_repair_request_id bigint;
BEGIN
    -- Создание заявки на ремонт
    INSERT INTO public.service_repairrequest(problem, execution_deadline, cost)
    VALUES (p_problem, p_execution_deadline, p_cost)
    RETURNING id INTO v_repair_request_id;

    -- Добавление выбранных услуг к заявке
    FOREACH v_service_id IN ARRAY p_services
    LOOP
        INSERT INTO public.service_repairrequest_services(repairrequest_id, service_id)
        VALUES (v_repair_request_id, v_service_id);
    END LOOP;
END;
$$;

CREATE OR REPLACE PROCEDURE public.create_repair_request(
    p_problem TEXT,
    p_execution_deadline DATE,
    p_cost NUMERIC(10, 2),
    p_services INTEGER[]
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_repair_request_id bigint;
BEGIN
    -- Создание заявки на ремонт
    INSERT INTO public.service_repairrequest(problem, execution_deadline, cost)
    VALUES (p_problem, p_execution_deadline, p_cost)
    RETURNING id INTO v_repair_request_id;

    -- Добавление выбранных услуг к заявке
    FOREACH v_service_id IN ARRAY p_services
    LOOP
        INSERT INTO public.service_repairrequest_services(repairrequest_id, service_id)
        VALUES (v_repair_request_id, v_service_id);
    END LOOP;
END;
$$;

-- Функция для расчета общей стоимости услуг в заявке на ремонт
CREATE OR REPLACE FUNCTION public.calculate_repair_cost(
    p_repair_request_id bigint
)
RETURNS NUMERIC(10, 2)
AS $$
DECLARE
    v_total_cost NUMERIC(10, 2) := 0;
BEGIN
    SELECT
        COALESCE(SUM(ss.price), 0)
    INTO
        v_total_cost
    FROM
        public.service_repairrequest sr
    JOIN
        public.service_repairrequest_services srs ON sr.id = srs.repairrequest_id
    JOIN
        public.service_service ss ON srs.service_id = ss.id
    WHERE
        sr.id = p_repair_request_id;

    RETURN v_total_cost;
END;
$$ LANGUAGE plpgsql;

-- Функция для получения информации о пользователе с автомобилем
CREATE OR REPLACE FUNCTION public.get_user_car_info(
    p_user_id bigint
)
RETURNS TABLE (
    username VARCHAR(150),
    email VARCHAR(254),
    license_plate VARCHAR(10),
    brand VARCHAR(100),
    vin VARCHAR(17)
)
AS $$
BEGIN
    RETURN QUERY
    SELECT
        au.username,
        au.email,
        ac.license_plate,
        ac.brand,
        ac.vin
    FROM
        public.authenticate_user au
    JOIN
        public.authenticate_car ac ON au.car_id = ac.id
    WHERE
        au.id = p_user_id;
END;
$$ LANGUAGE plpgsql;
