# Generated by Django 4.2.7 on 2023-11-15 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_order_created_time_repairrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 1, 20, 1, 342380)),
        ),
    ]
