# Generated by Django 4.2.7 on 2023-12-02 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 7, 38, 33, 682590)),
        ),
    ]
