# Generated by Django 4.2.7 on 2023-12-02 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 7, 40, 21, 93079)),
        ),
        migrations.AlterField(
            model_name='spare',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
