# Generated by Django 4.2.7 on 2023-12-02 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_order_created_time_alter_spare_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 7, 41, 14, 237298)),
        ),
        migrations.AlterField(
            model_name='spare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spares/'),
        ),
    ]
