# Generated by Django 4.2.7 on 2023-12-05 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_order_user_alter_order_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='spare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='service.spare'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 11, 1, 1, 100380)),
        ),
    ]
