# Generated by Django 4.2.7 on 2023-12-13 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_order_created_time_alter_orderitem_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_chart',
            field=models.ImageField(blank=True, null=True, upload_to='order_status_charts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 20, 48, 36, 640523)),
        ),
    ]
