# Generated by Django 4.2.7 on 2023-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_car_employee_user_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('not determined', 'NOT DETERMINED'), ('support ', 'SUPPORT'), ('mechanic', 'MECHANIC')], default=('not determined', 'NOT DETERMINED')),
        ),
    ]
